dlibrary(DT)
library(leaflet)
ui <- fluidPage(
  titlePanel("Data Science Final Project"),
  mainPanel(    
    leafletOutput(outputId = "college_map", width="600px",height="350px"),
    tags$hr(),
    tabsetPanel(
      tabPanel("Introduction",
               tags$h3("A. Context"),
               tags$h4("This dataset is created for prediction of Graduate Admissions from an Indian perspective."),
               tags$hr(),
               tags$h3("B. Content"),
               tags$h4("The dataset contains several parameters which are considered important during the application for Masters Programs."),
               tags$hr(),
               tags$h3("C. The parameters included are :"),
               tags$h4("1. GRE Scores"),
               tags$h4("2. TOEFL Scores"),
               tags$h4("3. University Rating"),
               tags$h4("4. Statement of Purpose and Letter of Recommendation Strength"),
               tags$h4("5. Undergraduate GPA"),
               tags$h4("6. Research Experience"),
               tags$h4("7. Chance of Admit"),
               tags$hr(),
               tags$h3("D. Reference"), 
               tags$a("https://www.kaggle.com/mohansacharya/graduate-admissions"),
               tags$hr(),
               tags$h3("E. Group members:"),
               tags$h4("105703031 資科三 黃子恒"),
               tags$h4("105703030 資科三 劉上銓"),
               tags$h4("105703053 資科三 陳則明"),
               tags$h4("107753033 資科碩一 李柏彥"),
               tags$hr()),
      tabPanel("Data Description",
               tags$h3("It shows the detail of data"),
               tags$h4("1. Serial No.: "),
               tags$h5("申請者的編號，從 1 到 500 號，共 500 人。"),
               tags$hr(),
               tags$h4("2. GRE. Score: "),
               tags$h5("GRE 成績，分為 verbal 和 quantitative 兩部份，各 170 分，本資料中最低分 290 分，最高分 340 分，平均 316 分。"),
               tags$hr(),
               tags$h4("3. TOEFL. Score: "),
               tags$h5("托福成績，分為聽說讀寫四科，每科各 30 分，本資料中最低分 92 分，最⾼分 120 分，平均 107。"),
               tags$hr(),
               tags$h4("4. University. Rating: "),
               tags$h5("大學排名，分為五個等級，最低等為 1，最高等為 5。"),
               tags$hr(),
               tags$h4("5. SOP: "),
               tags$h5("Statement of purpose 申請動機，最低 1 分，最高 5 分。"),
               tags$hr(),
               tags$h4("6. LOR: "),
               tags$h5("Letter of recommendation 推薦信強度，最低 1 分，最高 5 分。"),
               tags$hr(),
               tags$h4("7. CGPA: "),
               tags$h5("Undergraduate GPA 在校成績，最⾼分 10 分，本資料中最⾼ 9.92，最低 6.8，平均 8.58。"),
               tags$hr(),
               tags$h4("8. Research: "),
               tags$h5("申請者是否發表研究論⽂或相關著作，未發表為 0，有發表為 1。"),
               tags$hr(),
               tags$h4("9. Chance. of. Admit: "),
               tags$h5("申請者錄取 UCLA 的機率。"),
               tags$hr(),
               verbatimTextOutput("data_describe"),
               tags$hr()),
      tabPanel("Histogram",
               plotOutput("histogram_plot", height = "600px"),
               tags$hr(),
               tags$h4("1. GRE. Score: "),
               tags$h5("GRE 的平均數為 316.68 分。從圖中可以看出在 310 ~ 315 區間以及 320 ~ 325 區間有一個高峰，顯示絕大多數學生的分數落在 320 分附近。"),
               tags$hr(),
               tags$h4("2. TOEFL. Score: "),
               tags$h5("TOEFL 的平均分數為 107.19 分。大多數學生的成績位於 100 ~ 110 分的區間內，其中又以考取 105 ~ 110 分的學生人數為最多。"),
               tags$hr(),
               tags$h4("4. University. Rating: "),
               tags$h5("資料將 University Rating 分為 5 個級距，大多數的申請人來自於排名位於中段的學校。只有極少數的人來自排名位於後段的學校。"),
               tags$hr(),
               tags$h4("5. SOP: "),
               tags$h5("SOP 分為五個級距，大多數申請人的 SOP 落在 3 ~ 4 的級距內。"),
               tags$hr(),
               tags$h4("6. LOR: "),
               tags$h5("LOR 分為五個級距，大多數申請人的 LOR 落在 3 ~ 4 的級距內。"),
               tags$hr(),
               tags$h4("7. CGPA: "),
               tags$h5("大學的 CGPA 分為 10 個級距，申請人最低的 CGPA 落在等級 7 的地方，而大多數的人則是落在 8 ~ 9 的級距內。"),
               tags$hr()),
      tabPanel("Histogram with Research factor", 
               p(),
               helpText("Please choose one attribute"),
               selectInput("xaxis2", "x axis", c("GRE.Score","TOEFL.Score","LOR","SOP","CGPA","Chance.of.Admit"), selected = "GRE.Score"),
               plotOutput("histogram_factor_plot", height = "400px"),
               tags$hr()
               ),
      tabPanel("Scatter Plot",
               tags$h3("Describe the relationship between attribute and chance of admit"), 
               helpText("Please choose one attribute"),
               selectInput("xaxis", "x axis", c("GRE.Score","TOEFL.Score","LOR","SOP","CGPA","Research"), selected = "GRE.Score"),
               plotOutput("scatter_plot", height = "600px"), 
               tags$hr(),
               tags$h3("1. GRE. Score: "),
               tags$h4("普遍而言，GRE成績越高，錄取機率越高。"),
               tags$hr(),
               tags$h3("2. TOEFL. Score: "),
               tags$h4("TOEFL成績越高，錄取機率越高。"),
               tags$hr(),
               tags$h3("3. University. Rating: "),
               tags$h4("學校排行與錄取機率的大小並沒有很大的關聯性。"),
               tags$hr(),
               tags$h3("4. SOP: "),
               tags$h4("申請動機越高分，錄取機率越大。"),
               tags$hr(),
               tags$h3("5. LOR: "),
               tags$h4("推薦信強度越高，錄取機率越高。"),
               tags$hr(),
               tags$h3("6. CGPA: "),
               tags$h4("在校成績越高，很明顯的錄取機率越高。"),
               tags$hr(),
               tags$h3("7. Research: "),
               tags$h4("是否有論文的發表與錄取機率雖有關聯，但卻沒有很大的影響。"),
               tags$hr()),
      tabPanel("Scatter Plot with factor",
               helpText("Please choose one attribute for factor"),
               selectInput("factor", "factor", c("Research", "University.Rating"), selected = "Research"),
               helpText("Please choose one attribute for x axis"),
               selectInput("xaxis3", "x axis", c("GRE.Score","TOEFL.Score","CGPA"), selected = "GRE.Score"),
               plotOutput("scatter_factor_plot", height = "400px", width = "600px"), 
               tags$hr()),
      tabPanel("Radar Plot",
               tags$h4("Chance.of.Admit >= 0.7 --> 'high'"),
               tags$h4("0.5 <= Chance.of.Admit < 0.7 --> 'median'"),
               tags$h4("Chance.of.Admit < 0.5 --> 'low'"),
               plotOutput("radar_plot", width = "600px", height = "600px"),
               tags$hr()),
      tabPanel("Box plot",
               helpText("Please choose one attribute for factor"),
               selectInput("factor2", "factor", c("University.Rating", "Research"), selected = "University.Rating"),
               plotOutput("box_factor_plot", height = "400px", width = "600px"), 
               tags$hr()),
      tabPanel("Correlation Plot",
               tags$img(src = 'correlation.png', width = "500px", height = "500px"),
               tags$h4("從 Correlation plot 可以看出 GRE、TOEFL 成績以及大學 GPA 與錄取率有很大的相關性。
                       GRE、TOEFL 成績與錄取率的相關係數約為 0.8，大學GPA與錄取率的相關係數則將近0.9。
                       而 Research 與錄取率的相關係數只有 0.55，表示相對於其他條件，申請人是否具有研究經驗可能不是那麼的重要。
                       另外 GRE、TOEFL 成績以及大學 GPA 兩倆之間的相關程度也很高，
                       表示申請人在大學學業成績的表現也反映在入學考試以及語言成績上。"),
               tags$hr()),
      tabPanel("Classification",
               tags$h3("Assumption"),
               tags$h4("Chance.of.Admit >= 0.9 --> 'Admission'"),
               tags$h4("Chance.of.Admit < 0.9 --> 'Reject'"),
               tags$hr(),
               DT::dataTableOutput('classification_table')
               ),
      tabPanel("Prediction",
               DT::dataTableOutput('regression_table')
               ),
      tabPanel("Cluster",
               tags$h3("Step1: 嘗試不同距離公式來分群，並找出最佳群數"),
               tags$h4("a. SSE method, best cluster number: 2"),
               tags$img(src = 'SSE_cluster_num.png', width = "450px", height = "300px"),
               tags$hr(),
               tags$h4("b. Silhouette method, best cluster number: 2"),
               tags$img(src = 'Silhouette_cluster_num.png', width = "450px", height = "300px"),
               tags$hr(),
               tags$h4("c. Gap method, best cluster numver: 5"),
               tags$img(src = 'Gap_cluster_num.png', width = "450px", height = "300px"),
               tags$hr(),
               tags$h4("d. 最後選擇 2 來當群的數量"),
               tags$hr(),
               tags$h3("Step2: 以 2 作為最佳群數，做出 Hierarchical clustering"),
               tags$h4("Tree_cluster, cluster num: 2"),
               tags$img(src = 'tree_cluster.png', width = "450px", height = "300px"),
               tags$hr(),
               tags$h3("Step3: 以 2 作為最佳群數，做 k-means 分群"),
               tags$img(src = 'raw_2.png', width = "450px", height = "300px"),
               tags$hr()
              ),
      tabPanel("Crawler",
               tags$h3("Studyabroad in PTT 共 825 篇心得文，Try to find some latent variable"),
               tags$h4("下圖是前 50 出現頻率的字，除了可量化的變數外，以及『教授、研究』等前五十字重要外，
                        我們也可以發現其他隱藏的加分經驗，例如出現『中研院(278次)、博士班(276次)、作品集(251次)、書卷(221次)、補習(220次)』等
                       ，都能幫助申請者錄取好學校"),
               tags$img(src = 'word_cloud2.jpg', width = "550px", height = "350px"),
               tags$hr(),
               tags$img(src = 'wordcount.png', width = "800px", height = "800px"))
    )
  )
)
